apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: griph-blog
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: griph-blog
        namespace: griph-blog
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc