apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: griph-blog
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: griph-blog
        namespace: griph-blog
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: rowan-blog
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: rowan-blog
        namespace: rowan-blog
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc
            
---


apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: ancestry-app
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: ancestry-app
        namespace: hiwraeden
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: ancestry-db
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: ancestry-db
        namespace: hiwraeden
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: snek-bot
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: snek-bot
        namespace: snek-bot
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: image-gallery
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: image-gallery
        namespace: image-gallery
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: kobot
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: kobot
        namespace: kobot
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc
