apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
    name: flux-system
    namespace: flux-system
spec:
    interval: 5m
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
    update:
        strategy: Setters
        path: ./apps
    git:
        commit:
            author:
                name: fluxcdbot
                email: fluxcdbot@users.noreply.github.com
            messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'