apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
    name: griph-blog
    namespace: griph-blog
spec:
    interval: 5m
    image: ghcr.io/griph72/griph-blog
    secretRef:
        name: github-regcred
    accessFrom:
        namespaceSelectors:
            - matchLabels: {}

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
    name: rowan-blog
    namespace: rowan-blog
spec:
    interval: 5m
    image: ghcr.io/rowan324/blog
    secretRef:
        name: github-regcred
    accessFrom:
        namespaceSelectors:
            - matchLabels: {}

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
    name: ancestry-server
    namespace: hiwraeden
spec:
    interval: 5m
    image: ghcr.io/hiwraeden/ancestry-server
    secretRef:
        name: github-regcred
    accessFrom:
        namespaceSelectors:
            - matchLabels: {}

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
    name: ancestry-ui
    namespace: hiwraeden
spec:
    interval: 5m
    image: ghcr.io/hiwraeden/ancestry-ui
    secretRef:
        name: github-regcred
    accessFrom:
        namespaceSelectors:
            - matchLabels: {}

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
    name: snek-bot
    namespace: snek-bot
spec:
    interval: 5m
    image: ghcr.io/opentoucan/snek-bot
    secretRef:
        name: github-regcred
    accessFrom:
        namespaceSelectors:
            - matchLabels: {}

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
    name: kobot
    namespace: kobot
spec:
    interval: 5m
    image: ghcr.io/opentoucan/kobot
    secretRef:
        name: github-regcred
    accessFrom:
        namespaceSelectors:
            - matchLabels: {}