apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
    name: griph-blog
    namespace: griph-blog
spec:
    interval: 5m
    image: ghcr.io/griph72/griph-blog
    secretRef:
        name: github-regcred
    accessFrom:
        namespaceSelectors:
            - matchLabels: {}