apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: griph-blog
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: griph-blog
        namespace: griph-blog
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: rowan-blog
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: rowan-blog
        namespace: rowan-blog
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc
            
---


apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: ancestry-server
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: ancestry-server
        namespace: hiwraeden
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: ancestry-ui
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: ancestry-ui
        namespace: hiwraeden
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
    name: snek-bot
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: snek-bot
        namespace: snek-bot
    filterTags:
        pattern: '^RELEASE\.(?P<timestamp>.*)$'
        extract: '$timestamp'
    policy:
        alphabetical:
            order: asc
