apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: hiwraeden
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
              name: nginx-tcp
              protocol: TCP

      volumes:
        - name: config
          configMap:
            name: nginx-conf
            items:
              - key: "nginx.conf"
                path: "/etc/nginx/conf.d/default.conf"