apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: hiwraeden
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
              name: nginx-tcp
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-conf