apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: hiwraeden
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "wo5daT6E2hMgVi"
          ports:
            - containerPort: 5432
              name: postgres-tcp
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc