apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: hiwraeden
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: postgres-tcp
      protocol: TCP
      name: postgres-svc-tcp