apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: hiwraeden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-triple-replica
  resources:
    requests:
      storage: 1Gi