apiVersion: v1
kind: Service
metadata:
  name: ancestry-server-service
  namespace: hiwraeden
  labels:
    app: ancestry-server
spec:
  ports:
    - port: 8000
      targetPort: server-tcp
      protocol: TCP
      name: server-svc-tcp
  selector:
    app: ancestry-server
