apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobot
  namespace: kobot
  labels:
    app: kobot
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kobot
  template:
    metadata:
      labels:
        app: kobot
    spec:
      containers:
        - name: bot
          image: ghcr.io/opentoucan/kobot:release.2025-02-01T16-39-45 # {"$imagepolicy": "flux-system:kobot"}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: kobot-config-volume
              subPath: application.properties
              mountPath: /application.properties
      volumes:
        - name: kobot-config-volume
          configMap:
            name: kobot-config
