apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobot
  namespace: kobot
  labels:
    app: kobot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kobot
  template:
    metadata:
      labels:
        app: kobot
    spec:
      containers:
        - name: bot
          image: ghcr.io/opentoucan/kobot:RELEASE.2024-04-20T19-37-44 # {"$imagepolicy": "flux-system:kobot"}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
          - name: kobot-config-volume
            subPath: application.properties
            mountPath: /application.properties
      volumes:
      - name: kobot-config-volume
        configMap:
          name: kobot-config