apiVersion: apps/v1
kind: Deployment
metadata:
  name: snek-bot
  namespace: snek-bot
  labels:
    app: snek-bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app:  snek-bot
  template:
    metadata:
      labels:
        app:  snek-bot
    spec:
      imagePullSecrets:
        - name: github-regcred
      containers:
        - name: snek-bot
          image: ghcr.io/opentoucan/snek-bot:RELEASE.2024-03-28T23-48-02 # {"$imagepolicy": "flux-system:snek-bot"}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: discord-token
                key: token
