apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: sensor-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-triple-replica
  resources:
    requests:
      storage: 1Gi