apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-pvc
  namespace: image-gallery
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-triple-replica
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: image-gallery
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-triple-replica
  resources:
    requests:
      storage: 500Mi